/*
 * This source file was generated by the Gradle 'init' task
 */
package laprak3;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello World!");
    }
}
